.include <bsd.own.mk>

SUBDIR	+=	filter-clamav
SUBDIR	+=	filter-dkim-signer
SUBDIR	+=	filter-dnsbl
#SUBDIR	+=	filter-lua
SUBDIR	+=	filter-monkey
SUBDIR	+=	filter-pause
SUBDIR	+=	filter-perl
SUBDIR	+=	filter-python
SUBDIR	+=	filter-spamassassin
SUBDIR	+=	filter-stub
SUBDIR	+=	filter-trace
SUBDIR	+=	filter-void


.include <bsd.subdir.mk>
