.\"
.\" Copyright (c) 2015, 2016 Joerg Jung <jung@openbsd.org>
.\"
.\" Permission to use, copy, modify, and distribute this software for any
.\" purpose with or without fee is hereby granted, provided that the above
.\" copyright notice and this permission notice appear in all copies.
.\"
.\" THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
.\" WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
.\" MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
.\" ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
.\" WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
.\" ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
.\" OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
.\"
.Dd $Mdocdate: May 16 2016 $
.Dt FILTER-PAUSE 8
.Os
.Sh NAME
.Nm filter-pause
.Nd smtpd filter to pause on new connections
.Sh SYNOPSIS
.Nm
.Op Fl dv
.Op Fl s Ar seconds
.Sh DESCRIPTION
.Nm
is a filter for
.Xr smtpd 8
which can be used to pause on new connections before emitting the standard
initial SMTP greeting.
This is useful to avoid the so called
.Dq slamming
technique used by some senders of spam mails.
.Pp
The options are as follows:
.Bl -tag -width "-s seconds"
.It Fl d
Debug mode, if this option is specified,
.Nm
will run in the foreground and log to
.Em stderr .
.It Fl s Ar seconds
Set the number of
.Ar seconds
to pause before sending the initial greeting.
The accepted values are within the range of 1s and 300s.
.Pp
The default
.Ar seconds
value is 5s.
.It Fl v
Produce more verbose output.
.El
.Pp
.Nm
runs by default in a chroot.
.Pp
The debug and verbose options given with the
.Xr smtpd 8
invocation are intially passed to
.Nm .
.Pp
With
.Nm
enabled,
.Xr smtpd 8
simply waits the specified amount of
.Ar seconds
on each new connection.
If the remote server starts sending SMTP commands before the greeting, the
connection is rejected.
Otherwise, the connection is accepted and normally processed.
.Sh SEE ALSO
.Xr filter_api 3 ,
.Xr smtpd.conf 5 ,
.Xr smtpd 8
.Sh STANDARDS
.Rs
.%A J. Klensin
.%D October 2008
.%R RFC 5321
.%T Simple Mail Transfer Protocol
.Re
.Sh HISTORY
The first version of
.Nm
was written in 2015.
.Sh AUTHORS
.An Joerg Jung Aq Mt jung@openbsd.org
