.include <bsd.own.mk>

SUBDIR	 =	table-ldap
SUBDIR	+=	table-mysql
SUBDIR	+=	table-postgres
SUBDIR	+=	table-python
SUBDIR	+=	table-sqlite
SUBDIR	+=	table-socketmap
SUBDIR	+=	table-stub

.include <bsd.subdir.mk>
