.\"
.\" Copyright (c) 2015, 2016 Joerg Jung <jung@openbsd.org>
.\"
.\" Permission to use, copy, modify, and distribute this software for any
.\" purpose with or without fee is hereby granted, provided that the above
.\" copyright notice and this permission notice appear in all copies.
.\"
.\" THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
.\" WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
.\" MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
.\" ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
.\" WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
.\" ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
.\" OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
.\"
.Dd $Mdocdate: April 09 2016 $
.Dt FILTER-DNSBL 8
.Os
.Sh NAME
.Nm filter-dnsbl
.Nd smtpd filter for DNSBL checks
.Sh SYNOPSIS
.Nm
.Op Fl dv
.Op Fl h Ar host
.Op Fl w Ar host
.Sh DESCRIPTION
.Nm
is a filter for
.Xr smtpd 8
which can be used to check new connections against a
DNS-based Blackhole List (DNSBL) and optional a DNS-based Whitelist (DNSWL).
.Pp
The options are as follows:
.Bl -tag -width "-h host"
.It Fl d
Debug mode, if this option is specified,
.Nm
will run in the foreground and log to
.Em stderr .
.It Fl h Ar host
Set the DNSBL
.Ar host
to be queried.
.Pp
The default
.Ar host
is dnsbl.sorbs.net.
.It Fl v
Produce more verbose output.
.It Fl w Ar host
Set the DNSWL
.Ar host
to be queried.
.Pp
The default is to not query a DNSWL
.Ar host .
.El
.Pp
The debug and verbose options given with the
.Xr smtpd 8
invocation are intially passed to
.Nm .
.Pp
The remote IP address of new connections is used in a DNS query against the
DNSBL and optional DNSWL.
If the remote address is listed in the DNSBL, the connection is rejected,
otherwise accepted.
If the optional DNSWL host is given, it is queried first and if the remote
address is listed the connection is accepted (without checking the DNSBL).
.Sh SEE ALSO
.Xr filter_api 3 ,
.Xr smtpd.conf 5 ,
.Xr smtpd 8
.Sh HISTORY
The first version of
.Nm
was written in 2013.
.Sh AUTHORS
.An Eric Faurot Aq Mt eric@openbsd.org
