.\"
.\" Copyright (c) 2015 Bernard Spil <brnrd@FreeBSD.org>
.\" Copyright (c) 2015, 2016 Joerg Jung <jung@openbsd.org>
.\"
.\" Permission to use, copy, modify, and distribute this software for any
.\" purpose with or without fee is hereby granted, provided that the above
.\" copyright notice and this permission notice appear in all copies.
.\"
.\" THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
.\" WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
.\" MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
.\" ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
.\" WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
.\" ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
.\" OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
.\"
.Dd $Mdocdate: May 18 2016 $
.Dt FILTER-DKIM-SIGNER 8
.Os
.Sh NAME
.Nm filter-dkim-signer
.Nd smtpd filter to add DKIM signatures
.Sh SYNOPSIS
.Nm
.Op Fl Cdv
.Op Fl c Ar path
.Op Fl D Ar domain
.Op Fl p Ar private-key
.Op Fl s Ar selector
.Sh DESCRIPTION
.Nm
is a filter for
.Xr smtpd 8
which can be used to add rsa-sha256 DKIM signatures to
SMTP headers
.Pp
The options are as follows:
.Bl -tag -width "-p private-key"
.It Fl C
No
.Xr chroot 2
mode, if this option is specified,
.Nm
will not run in a chroot.
.It Fl c Ar path
Set the chroot
.Ar path .
.Pp
The default
.Ar path
is
.Pa /var/empty
(compile option).
.It Fl D Ar domain
Set the DKIM
.Ar domain
to be added.
.Pp
The default
.Ar domain
is retrieved with gethostname().
.It Fl d
Debug mode, if this option is specified,
.Nm
will run in the foreground and log to
.Em stderr .
.It Fl p Ar private-key
The file-name that contains the RSA
.Ar private-key
to be used for signing
.Pp
The default
.Ar private-key
is /etc/ssl/private/rsa.private
.It Fl s Ar selector
Set the DKIM
.Ar selector
.Pp
The default
.Ar selector
is "default"
.It Fl v
Produce more verbose output.
.El
.Pp
.Nm
runs by default in a chroot.
.Pp
The debug and verbose options given with the
.Xr smtpd 8
invocation are intially passed to
.Nm .
.Pp
With
.Nm
enabled, an rsa-sha256 DKIM signature header is added to mails passing
through the filter.
.Sh SEE ALSO
.Xr chroot 2 ,
.Xr filter_api 3 ,
.Xr smtpd.conf 5 ,
.Xr smtpd 8
.Sh HISTORY
The first version of
.Nm
was written in 2014.
.Sh AUTHORS
.An Sunil Nimmagadda
