CFLAGS+=-Wall -Wstrict-prototypes -Wmissing-prototypes -Wmissing-declarations -Wshadow -Wpointer-arith -Wcast-qual -Wsign-compare
PROG=	filter-regex
SRCS=	filter_regex.c
NOMAN=	noman

uninstall:
	rm -f ${BINDIR}/filter-regex

.include <bsd.prog.mk>
